# -*- coding: utf-8 -*-
"""AI_HandPose_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vNa0vdPraMwIZyLS4NC00F4b9CYH7Slq

**Install Dependencies**
"""

!pip3 install PyGrabber

!pip3 install comtypes

!pip3 install pymf

!pip install mediapipe opencv-python

"""**Import Libraries**"""

import mediapipe as mp
import cv2 
import numpy as np
import uuid
import os

mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands

"""**Input Images**"""

#cap = cv2.VideoCapture(0)

# Check if the webcam is opened correctly
#if not cap.isOpened():
    #raise IOError("Cannot open webcam")

with mp_hands.Hands(min_detection_confidence=0.8, min_tracking_confidence=0.5) as hands:
  while cap.isOpened():
    ret, frame = cap.read()
    #Detections
    image = cv2.cvtColor(frame, cv2.COLOR_BGR2R)
    
    #set flag
    image.flags.writable = False
    
    #Detections
    results = hands.process(image)+
    
    #Set flag to true
    image.flags.writable = True
    
    #RGB 2 BGR
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)

    #Detections
    print(results)


    cv2.imshow('Hand Tracking',frame)
    if cv2.waitKey(10) & 0xFF == ord('q'):
     break

cap.release()
cv2.destroyAllWindows()